#!/usr/bin/env bash
# Script per automatizzare il caricamento del modulo joystick_ng

if [ $UID != 0 ]; then
    echo "Devi essere root!"
    exit 1
fi

rmmod usbhid             &> /dev/null
rmmod hid                &> /dev/null
rmmod joystick_ng        &> /dev/null

insmod ./joystick_ng.ko
modprobe hid
modprobe usbhid
